apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinned-sa
  namespace: pinned
  annotations:
    iam.gke.io/gcp-service-account: pinned-backend@project-9c52df7f-9c59-4739-9b4.iam.gserviceaccount.com
