apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: pinned
data:
  PORT: "5001"
  NODE_ENV: "production"
  DB_HOST: "127.0.0.1"   # Cloud SQL Auth Proxy sidecar
  DB_PORT: "5432"
  DB_NAME: "pinned_db"
