apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pinned
  annotations:
    cloud.google.com/backend-config: '{"default": "pinned-backend-config"}'
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
