apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: pinned

images:
  - name: REGION-docker.pkg.dev/PROJECT_ID/pinned/backend
    newName: asia-northeast3-docker.pkg.dev/project-9c52df7f-9c59-4739-9b4/pinned-app/backend
    newTag: dev-2452588f49f97fe8d97ab63b3dbb0485ebf85147
