apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/serviceaccount.yaml
  - backend/backendconfig.yaml
  - backend/configmap.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - backend/deployment.yaml
  - network-policy/default-deny.yaml
  - network-policy/backend-allow.yaml

images:
  - name: REGION-docker.pkg.dev/PROJECT_ID/pinned/backend
    newName: asia-northeast3-docker.pkg.dev/project-9c52df7f-9c59-4739-9b4/pinned-app/backend
    newTag: latest
