apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/description: >
      pinned 네임스페이스의 모든 컨테이너는 권한 상승이 금지됩니다.
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-allow-privilege-escalation
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: [pinned]
      validate:
        message: "securityContext.allowPrivilegeEscalation: false 가 필수입니다."
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
