apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pinned-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/meungenie/pinned.git
    targetRevision: dev
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: pinned-dev
  syncPolicy:
    automated:
      prune: true      # git에서 삭제된 리소스 자동 제거
      selfHeal: true   # 클러스터가 git 상태와 다르면 자동 복구
    syncOptions:
      - CreateNamespace=true
