apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: pinned-dev

images:
  - name: REGION-docker.pkg.dev/PROJECT_ID/pinned/backend
    newName: asia-northeast3-docker.pkg.dev/project-9c52df7f-9c59-4739-9b4/pinned-app/backend
    newTag: dev-0a6d4e44d2d292041a231623bab272b290278262
