apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../namespace-dev.yaml

namespace: pinned-dev

images:
  - name: REGION-docker.pkg.dev/PROJECT_ID/pinned/backend
    newName: asia-northeast3-docker.pkg.dev/project-9c52df7f-9c59-4739-9b4/pinned-app/backend
    newTag: latest   # CI가 dev-{sha}로 자동 업데이트
