apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: pinned-dev

images:
  - name: REGION-docker.pkg.dev/PROJECT_ID/pinned/backend
    newName: asia-northeast3-docker.pkg.dev/project-9c52df7f-9c59-4739-9b4/pinned-app/backend
    newTag: dev-cf3c6d7b6c2d10a4b0e50951c51786509e959b7a
